-- MANUAL REVIEW ONLY. Never executed by the application. Requires existing public.users(id integer).
BEGIN;
CREATE TABLE sales_workspaces (id uuid PRIMARY KEY, name text NOT NULL CHECK(length(name) BETWEEN 1 AND 200));
CREATE TABLE sales_memberships (workspace_id uuid REFERENCES sales_workspaces(id), user_id integer REFERENCES users(id), role text NOT NULL CHECK(role IN ('owner','admin','member','viewer')), PRIMARY KEY(workspace_id,user_id));
CREATE TABLE sales_companies (workspace_id uuid REFERENCES sales_workspaces(id), id uuid NOT NULL, name text NOT NULL CHECK(length(name) BETWEEN 1 AND 200), version integer NOT NULL DEFAULT 1, PRIMARY KEY(workspace_id,id));
CREATE TABLE sales_contacts (workspace_id uuid REFERENCES sales_workspaces(id), id uuid NOT NULL, name text NOT NULL CHECK(length(name) BETWEEN 1 AND 200), company_id uuid, version integer NOT NULL DEFAULT 1, PRIMARY KEY(workspace_id,id), FOREIGN KEY(workspace_id,company_id) REFERENCES sales_companies(workspace_id,id));
CREATE TABLE sales_leads (workspace_id uuid REFERENCES sales_workspaces(id), id uuid NOT NULL, title text NOT NULL CHECK(length(title) BETWEEN 1 AND 200), company_id uuid, contact_id uuid, version integer NOT NULL DEFAULT 1, PRIMARY KEY(workspace_id,id), FOREIGN KEY(workspace_id,company_id) REFERENCES sales_companies(workspace_id,id), FOREIGN KEY(workspace_id,contact_id) REFERENCES sales_contacts(workspace_id,id));
CREATE TABLE sales_processes (workspace_id uuid REFERENCES sales_workspaces(id), id uuid NOT NULL, title text NOT NULL CHECK(length(title) BETWEEN 1 AND 200), kind text NOT NULL CHECK(kind IN ('opportunity','task')), version integer NOT NULL DEFAULT 1, PRIMARY KEY(workspace_id,id), UNIQUE(workspace_id,id,kind));
CREATE TABLE sales_stages (workspace_id uuid REFERENCES sales_workspaces(id), id uuid NOT NULL, process_id uuid NOT NULL, title text NOT NULL CHECK(length(title) BETWEEN 1 AND 200), position integer NOT NULL CHECK(position BETWEEN 0 AND 10000), task_title text CHECK(length(task_title) BETWEEN 1 AND 200), version integer NOT NULL DEFAULT 1, PRIMARY KEY(workspace_id,id), UNIQUE(workspace_id,process_id,id), UNIQUE(workspace_id,process_id,position), FOREIGN KEY(workspace_id,process_id) REFERENCES sales_processes(workspace_id,id));
CREATE TABLE sales_opportunities (workspace_id uuid REFERENCES sales_workspaces(id), id uuid NOT NULL, title text NOT NULL CHECK(length(title) BETWEEN 1 AND 200), company_id uuid, contact_id uuid, process_id uuid NOT NULL, stage_id uuid NOT NULL, process_kind text NOT NULL DEFAULT 'opportunity' CHECK(process_kind='opportunity'), amount_cents bigint NOT NULL DEFAULT 0 CHECK(amount_cents BETWEEN 0 AND 9000000000000), version integer NOT NULL DEFAULT 1, PRIMARY KEY(workspace_id,id), FOREIGN KEY(workspace_id,company_id) REFERENCES sales_companies(workspace_id,id), FOREIGN KEY(workspace_id,contact_id) REFERENCES sales_contacts(workspace_id,id), FOREIGN KEY(workspace_id,process_id,process_kind) REFERENCES sales_processes(workspace_id,id,kind), FOREIGN KEY(workspace_id,process_id,stage_id) REFERENCES sales_stages(workspace_id,process_id,id));
CREATE TABLE sales_tasks (workspace_id uuid REFERENCES sales_workspaces(id), id uuid NOT NULL, title text NOT NULL CHECK(length(title) BETWEEN 1 AND 200), opportunity_id uuid, process_id uuid, stage_id uuid, process_kind text NOT NULL DEFAULT 'task' CHECK(process_kind='task'), status text NOT NULL DEFAULT 'todo' CHECK(status IN ('todo','doing','done')), version integer NOT NULL DEFAULT 1, CHECK((process_id IS NULL)=(stage_id IS NULL)), PRIMARY KEY(workspace_id,id), FOREIGN KEY(workspace_id,opportunity_id) REFERENCES sales_opportunities(workspace_id,id), FOREIGN KEY(workspace_id,process_id,process_kind) REFERENCES sales_processes(workspace_id,id,kind), FOREIGN KEY(workspace_id,process_id,stage_id) REFERENCES sales_stages(workspace_id,process_id,id));
CREATE TABLE sales_audit (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY, workspace_id uuid NOT NULL REFERENCES sales_workspaces(id), actor_id integer NOT NULL REFERENCES users(id), entity text NOT NULL, entity_id uuid NOT NULL, action text NOT NULL, at timestamptz NOT NULL DEFAULT now(), detail jsonb NOT NULL DEFAULT '{}');
CREATE INDEX sales_audit_workspace ON sales_audit(workspace_id,id);
CREATE TABLE sales_idempotency (workspace_id uuid NOT NULL REFERENCES sales_workspaces(id), actor_id integer NOT NULL REFERENCES users(id), key uuid NOT NULL, fingerprint jsonb NOT NULL, result jsonb NOT NULL, created_at timestamptz NOT NULL DEFAULT now(), PRIMARY KEY(workspace_id,actor_id,key));
-- No seeds, workspace provisioning or automatic membership. Operator provisions explicitly in isolated DB.
COMMIT;
