'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {dashboard}=require('../api/_dashboard');const now=1800000000000;
const row=flow=>({data:{history:{copywriter:[{content:'PRIVATE_CHAT',flow}]},flow:{task:'WRONG_TOP_LEVEL'}}});
test('projects history flow only; no raw conversations output or log text',()=>{const d=dashboard(row({status:'running',startedAt:now-1,nodes:[{role:'copywriter',status:'running',output:'PRIVATE_OUTPUT'}],log:[{t:now-1,k:'info',x:'PRIVATE_LOG'}]}),{},now);assert.equal(d.workflows[0].status,'unverified');assert.equal(d.agentStatus.copywriter.status,'unverified');assert.equal(d.activity[0].text,'Evento registrato');assert.doesNotMatch(JSON.stringify(d),/PRIVATE_|WRONG_TOP_LEVEL/)});
test('null invalid future dates are safe and never live',()=>{for(const date of [null,'bad',now+999999,0]){const d=dashboard(row({status:'running',startedAt:date,nodes:[null]}),{},now);assert.equal(d.workflows[0].status,'stale');assert.equal(d.workflows[0].startedAt,null)}});
test('counts before truncation; error node beyond limit prioritized',()=>{const nodes=Array.from({length:100},()=>({status:'done'}));nodes[99]={status:'error'};const d=dashboard(row({status:'done',nodes}),{},now);assert.equal(d.workflows[0].status,'error');assert.equal(d.workflows[0].progress.total,100);assert.equal(d.workflows[0].progress.error,1);assert.equal(d.workflows[0].nodes[0].status,'error');assert.equal(d.workflows[0].nodes.length,80)});
test('attention totals expose omitted errors and projects counted before preview',()=>{const d=dashboard({data:{projects:Array.from({length:110},(_,i)=>({id:String(i)})),history:{a:Array.from({length:30},()=>({flow:{status:'error'}}))}}} ,{},now);assert.equal(d.metrics.projects,110);assert.equal(d.metrics.attention,30);assert.equal(d.dataQuality.attentionOmitted,6);assert.equal(d.attention.length,24)});
function handler(user,query){const source=fs.readFileSync(require.resolve('../api/state'),'utf8');const calls=[];const sandbox={module:{exports:{}},require:id=>id==='./_auth'?{getSessionUser:()=>user}:id==='./_db'?{sql:()=>async(...args)=>{calls.push(args);return query()}}:require('../api/_dashboard')};vm.runInNewContext(source,sandbox);return {run:sandbox.module.exports,calls}}
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v},status(n){this.code=n;return this},json(v){this.body=v;return this}}}
test('dashboard auth/no-store neutral errors, no SQL before authentication',async()=>{let h=handler(null,()=>{throw Error('secret')});let r=response();await h.run({method:'GET',query:{view:'dashboard'}},r);assert.equal(r.code,401);assert.equal(h.calls.length,0);assert.equal(r.headers['Cache-Control'],'no-store');h=handler({name:'Demo'},()=>{throw Error('secret')});r=response();await h.run({method:'GET',query:{view:'dashboard'}},r);assert.equal(r.code,500);assert.doesNotMatch(JSON.stringify(r.body),/secret/)});
test('ordinary GET and POST patch retain contracts',async()=>{const state={history:{a:[]}};let h=handler({name:'Demo'},()=>[{data:state,updated_at:'stamp',updated_by:'Demo'}]),r=response();await h.run({method:'GET',query:{}},r);assert.equal(r.body.state,state);assert.equal(r.body.updatedAt,'stamp');h=handler({name:'Demo'},()=>[{updated_at:'stamp'}]);r=response();await h.run({method:'POST',query:{view:'dashboard'},body:{patch:{history:{a:[]},activeProject:'demo'}}},r);assert.equal(r.body.ok,true);assert.match(h.calls[0][0].join(''),/jsonb_set/);assert.equal(r.headers['Cache-Control'],undefined)});
