const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),test=require('node:test');
const html=fs.readFileSync(require('node:path').join(__dirname,'../control-center-v2.html'),'utf8');
const source=html.split('<script>')[1].split('</script>')[0];
function fn(name){let start=source.indexOf('  function '+name+'('),end=source.indexOf('\n  }',start);const line=source.indexOf('\n',start);if(source.slice(start,line).endsWith('}'))end=line-3;return source.slice(start,end+4)}
function context(){const c={data:{agentStatus:{},projects:[],workflows:[],dataQuality:{realtimeExecutionVerified:false}},UNASSIGNED:'__unassigned_workflows__',AGENTS:[],Date};vm.createContext(c);for(const n of ['esc','legacyProjection','projectItems','workflowTasks','executionCounts','projectPalette','projectColor','projectRank','orderedProjects'])vm.runInContext(fn(n),c);return c}
test('errors, pending and stale are not running; snapshot is not verified execution',()=>{const c=context();c.data.agentStatus={a:{status:'running'},b:{status:'error'},d:{status:'pending'},e:{status:'stale'}};assert.equal(c.executionCounts().recorded,1);assert.equal(c.executionCounts().verified,null);c.data.dataQuality.realtimeExecutionVerified=true;assert.equal(c.executionCounts().verified,1)});
test('project ownership is explicit; unassigned history is navigable separately',()=>{const c=context();c.data.workflows=[{id:'a',projectId:'client',nodes:[{id:'task'}]},{id:'b',nodes:[]}];assert.equal(c.projectItems('client')[0].id,'a');assert.equal(c.projectItems(c.UNASSIGNED)[0].id,'b');assert.equal(c.workflowTasks(c.data.workflows[0])[0].id,'task');assert.equal(c.projectItems('unknown').length,0)});
test('latest agent record wins even when history is traversed out of timestamp order',()=>{const c=context();const now=Date.now();const r=c.legacyProjection({state:{history:{one:[{flow:{status:'done',startedAt:now,nodes:[{role:'copywriter',status:'done'}]}}],two:[{flow:{status:'error',startedAt:now-100000,nodes:[{role:'copywriter',status:'error'}]}}]}}},{});assert.equal(r.agentStatus.copywriter.status,'done')});
test('project color and order match master for full descriptive names',()=>{const c=context();c.data.projects=[{name:'Doc Capital'},{name:'Aura — assistente personale AI'},{name:'Francesco Ilari — personal branding'}];assert.ok(c.orderedProjects()[0].name.startsWith('Aura'));assert.equal(c.projectColor(c.data.projects[1],3),'#23e69b');assert.equal(c.projectColor(c.data.projects[0],0),'#4da6ff')});
test('roster matches operational workspace ids and groups',()=>{const index=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');const roster=source.match(/var AGENTS=(\[.*?\n  \]);/s)[1];const original=index.match(/var AGENTS = (\[.*?\n  \]);/s)[1];const a=vm.runInNewContext(roster),b=vm.runInNewContext(original);assert.equal(a.length,b.length);assert.deepEqual(Array.from(a,x=>x.id),Array.from(b,x=>x.id))});
