const test=require('node:test');const assert=require('node:assert/strict');const pm=require('../lib/pm-demo.js');
test('seed isolates memory and identifies synthetic pilot',()=>{const a=pm.seed(),b=pm.seed();a.tasks[0].title='changed';assert.notEqual(a.tasks[0].title,b.tasks[0].title);assert.match(b.projects[0].note,/sintetici/);});
test('dependencies block start and completion without mutations',()=>{const s=pm.seed(),before=JSON.stringify(s);assert.throws(()=>pm.changeStatus(s,'t3','In corso'),/dipendenze/);assert.throws(()=>pm.changeStatus(s,'t3','Completato'),/dipendenze/);assert.equal(JSON.stringify(s),before);});
test('approval explicit, review-only and required for completion',()=>{const s=pm.seed();assert.throws(()=>pm.changeStatus(s,'t2','Completato'),/approvazione/);assert.throws(()=>pm.approve(s,'t2',false),/esplicitamente/);pm.approve(s,'t2',true);pm.changeStatus(s,'t2','Completato');pm.changeStatus(s,'t3','In corso');assert.equal(s.tasks[2].status,'In corso');assert.throws(()=>pm.approve(s,'t4',true),/revisione/);});
test('reopening protects dependent work and invalidates approval',()=>{const s=pm.seed();assert.throws(()=>pm.changeStatus(s,'t1','Da fare'),/dipendenti/);pm.changeStatus(s,'t2','Da fare');pm.changeStatus(s,'t1','Da fare');assert.equal(s.tasks[0].approved,false);});
const input={title:'Nuovo task',owner:'Team demo',due:'2026-10-20',project:'p1',subproject:'s2',dependencies:['t3'],approvalRequired:true,milestone:true,recurrence:'Settimanale'};
test('creation retains assignment and descriptive recurrence',()=>{const s=pm.seed(),t=pm.create(s,input);assert.equal(t.id,'t5');assert.equal(t.status,'Da fare');assert.equal(t.approvalRequired,true);assert.equal(t.milestone,true);assert.match(t.recurrence,/solo descrizione/);assert.deepEqual(t.dependencies,['t3']);});
test('invalid creation leaves memory intact',()=>{for(const patch of [{title:' '},{owner:''},{due:'2026-02-30'},{due:'not a date'},{project:'missing'},{subproject:'missing'},{dependencies:['missing']}]){const s=pm.seed();assert.throws(()=>pm.create(s,{...input,...patch}));assert.equal(s.tasks.length,4);assert.equal(s.nextId,5);}});
test('filters compose search, status, owner and milestones',()=>{const s=pm.seed();assert.equal(pm.filter(s,{query:'PILOTA',milestone:true}).length,2);assert.equal(pm.filter(s,{status:'Da fare',owner:'Elena Rossi',subproject:'s2'}).length,1);assert.equal(pm.filter(s,{query:'not found'}).length,0);});
test('unknown ids and statuses fail safely',()=>{const s=pm.seed();assert.throws(()=>pm.changeStatus(s,'missing','Da fare'),/non trovata/);assert.throws(()=>pm.changeStatus(s,'t1','Live'),/non valido/);});

test('HTML remains offline, accessible and avoids HTML injection sinks',()=>{const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');const html=fs.readFileSync(path.join(__dirname,'../radix-pm-concept.html'),'utf8');assert.match(html,/lang="it"/);assert.match(html,/connect-src 'none'/);assert.match(html,/aria-live="polite"/);assert.match(html,/prefers-reduced-motion/);assert.doesNotMatch(html,/https?:\/\/|fetch\(|localStorage|sessionStorage|innerHTML/);for(const match of html.matchAll(/<script>([\s\S]*?)<\/script>/g))new vm.Script(match[1]);assert.match(html,/src="lib\/pm-demo.js"/);});
test('approval is idempotent and full prerequisite chain can complete',()=>{const s=pm.seed();pm.approve(s,'t2',true);const length=s.tasks[1].history.length;pm.approve(s,'t2',true);assert.equal(s.tasks[1].history.length,length);pm.changeStatus(s,'t2','Completato');pm.changeStatus(s,'t3','Completato');pm.changeStatus(s,'t4','In revisione');pm.approve(s,'t4',true);pm.changeStatus(s,'t4','Completato');assert.ok(s.tasks.every(t=>t.status==='Completato'));});
