'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs');
const {createHandler,command}=require('../api/_sales'),{createStore}=require('../api/_sales_store');
const W='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',ID='33333333-3333-4333-8333-333333333333',S='44444444-4444-4444-8444-444444444444',K='55555555-5555-4555-8555-555555555555';
const body=(entity,action,data)=>({workspace:W,entity,action,data});
async function req({user={uid:1},store={},method='GET',query={workspace:W,entity:'companies'},data,headers={}}={}){let calls=0;const r={headers:{},setHeader(k,v){this.headers[k]=v;},status(v){this.code=v;return this;},json(v){this.body=v;return this;}};await createHandler({getSessionUser:()=>user,getStore:()=>{calls++;return store;}})({method,query,body:data,headers:{'content-type':'application/json','x-radix-sales':'1',...headers}},r);return {...r,calls};}
test('missing session fails before DB, no-store',async()=>{const r=await req({user:null});assert.equal(r.code,401);assert.equal(r.calls,0);assert.equal(r.headers['Cache-Control'],'no-store');});
test('invalid session/method rejected',async()=>{assert.equal((await req({user:{uid:'1'}})).code,401);assert.equal((await req({method:'DELETE'})).code,405);});
test('membership deny default; cross workspace and deleted user denied',async()=>{const store={membership:async w=>w===W?{role:'member'}:null};assert.equal((await req({store,query:{workspace:B,entity:'companies'}})).code,403);assert.equal((await req({store:{membership:async()=>null}})).code,403);});
test('viewer cannot write; member cannot configure processes',async()=>{for(const [role,entity,d] of [['viewer','companies',{name:'X'}],['member','processes',{title:'P',kind:'task'}]])assert.equal((await req({method:'POST',data:body(entity,'create',d),store:{membership:async()=>({role})}})).code,403);});
test('CSRF custom JSON header and cross-site gate',async()=>{for(const headers of [{'sec-fetch-site':'cross-site'},{'x-radix-sales':''},{'content-type':'text/plain'}])assert.equal((await req({method:'POST',headers})).code,403);});
test('strict validation identifiers fields stages version enums',()=>{for(const b of [body('companies','create',{name:'X',id:ID}),body('companies','create',{name:'X',workspace_id:B}),body('opportunities','update',{id:ID,version:1,stage_id:S}),body('__proto__','create',{}),body('companies','update',{id:ID,version:0,name:'X'}),body('tasks','create',{title:'X',process_id:ID}),body('opportunities','create',{title:'X',process_id:ID,stage_id:S,amount_cents:-1}),body('companies','create',{name:' '}),body('companies','create',{name:'x'.repeat(201)}),body('stages','create',{title:'X',process_id:ID}),body('tasks','create',{title:'X',status:'sent'}),body('processes','create',{title:'X',kind:'email'}),body('opportunities','transition',{id:ID,version:1,stage_id:S})])assert.throws(()=>command(b));});
test('server IDs and stable idempotency key',()=>{assert.match(command(body('companies','create',{name:'X'})).data.id,/^[a-f0-9-]{36}$/);const b=body('opportunities','transition',{id:ID,version:1,stage_id:S,key:K});const a=command(b),r=command(b);assert.equal(a.data.key,r.data.key);assert.notEqual(a.data.task_id,r.data.task_id);});
test('SQL adapter binds values and tenant/user guards single atomic statement',async()=>{const calls=[];const store=createStore(async(q,p)=>{calls.push([q,p]);return [{result:{id:ID}}];});await store.read({workspace:W,entity:'companies',offset:100},1);assert.ok(calls[0][0].includes('workspace_id=$1'));assert.match(calls[0][0],/JOIN users/);assert.deepEqual(calls[0][1],[W,1,100]);await store.command(command(body('companies','create',{name:"'); DROP TABLE users;--"})),1);assert.equal(calls.length,2);assert.equal(calls[1][0],'SELECT sales_command($1::uuid,$2::integer,$3::text,$4::text,$5::jsonb) AS result');assert.ok(!calls[1][0].includes('DROP'));});
test('DB errors safe mapping no internal leak',async()=>{for(const [code,status] of [['23503',409],['40001',409],['P0002',404],['42P01',503]]){const r=await req({method:'POST',data:body('companies','create',{name:'X'}),store:{membership:async()=>({role:'member'}),command:async()=>{throw Object.assign(new Error('private connection'),{code});}}});assert.equal(r.code,status);assert.ok(!JSON.stringify(r.body).includes('private'));}});
// Mocked atomic-store CONTRACT ONLY, not execution of PL/pgSQL.
function model(){let state={version:1,tasks:[],audit:[],keys:{}};return {snapshot:()=>structuredClone(state),async sql(q,p){const d=JSON.parse(p[4]),fp=JSON.stringify([d.id,d.version,d.stage_id]),old=state.keys[d.key];if(old){if(old.fp!==fp)throw Object.assign(new Error(),{code:'40001'});return [{result:old.result}];}const n=structuredClone(state);if(d.version!==n.version)throw Object.assign(new Error(),{code:'40001'});n.version++;n.tasks.push(d.task_id);if(d.failAudit)throw new Error('audit failure');n.audit.push(d.id);const result={id:d.id,version:n.version};n.keys[d.key]={fp,result};state=n;return [{result}];}};}
test('MOCK atomic contract replay once key collision conflict',async()=>{const m=model(),store=createStore(m.sql),b=body('opportunities','transition',{id:ID,version:1,stage_id:S,key:K});assert.deepEqual(await store.command(command(b),1),await store.command(command(b),1));assert.equal(m.snapshot().tasks.length,1);assert.equal(m.snapshot().audit.length,1);await assert.rejects(store.command(command({...b,data:{...b.data,stage_id:B}}),1),{code:'40001'});});
test('MOCK atomic contract rollback and stale write conflict',async()=>{const m=model(),store=createStore(m.sql),c=command(body('opportunities','transition',{id:ID,version:1,stage_id:S,key:K})),before=m.snapshot();await assert.rejects(store.command({...c,data:{...c.data,failAudit:true}},1));assert.deepEqual(m.snapshot(),before);await store.command(c,1);await assert.rejects(store.command({...c,data:{...c.data,key:B}},1),{code:'40001'});});
test('migration static contracts composite FK unique key and locks',()=>{const a=fs.readFileSync('migrations/sales/001_foundation.sql','utf8'),b=fs.readFileSync('migrations/sales/002_commands.sql','utf8');assert.ok(a.includes('FOREIGN KEY(workspace_id,process_id,stage_id)'));assert.ok(a.includes('PRIMARY KEY(workspace_id,actor_id,key)'));for(const x of ['pg_advisory_xact_lock','FOR UPDATE','FOR SHARE OF m,u','INSERT INTO sales_tasks','INSERT INTO sales_audit'])assert.ok(b.includes(x));assert.ok(!b.includes('SECURITY DEFINER'));});
