'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const {command,createHandler}=require('../api/_sales');
const W='11111111-1111-4111-8111-111111111111',P='22222222-2222-4222-8222-222222222222',S='33333333-3333-4333-8333-333333333333',T='44444444-4444-4444-8444-444444444444',ID='55555555-5555-4555-8555-555555555555';
class Node {
 constructor(tag){this.tag=tag;this.children=[];this.dataset={};this.listeners={};this.disabled=false;this.value='';this.textContent='';}
 append(...nodes){this.children.push(...nodes);} replaceChildren(...nodes){this.children=nodes;}
 setAttribute(k,v){this[k]=v;} addEventListener(k,fn){this.listeners[k]=fn;} focus(){} close(){this.open=false;} showModal(){this.open=true;} reset(){for(const n of this.querySelectorAll('input,select'))n.value='';}
 querySelectorAll(selector){const tags=selector.split(',').map(s=>s.trim().replace(/^#content /,''));return this.children.flatMap(n=>[...(tags.includes(n.tag)?[n]:[]),...n.querySelectorAll(selector)]);}
 querySelector(s){return this.querySelectorAll(s)[0];}
}
const response=(status=200,rows=[])=>({status,ok:status===200,json:async()=>({rows,error:status===200?undefined:'Denied'})});
function client(fetch=async()=>response()){
 const ids={};for(const id of ['status','error','editor-error','main','editor','editor-form','editor-fields','editor-title','content','workspace','membership','editor-cancel','refresh','navigation'])ids[id]=new Node(id==='workspace'?'select':id==='refresh'?'button':'div');
 ids['editor-form'].append(ids['editor-fields']);ids.editor.append(ids['editor-form']);
 const document={getElementById:id=>ids[id],createElement:tag=>new Node(tag),querySelectorAll:s=>[...ids.content.querySelectorAll(s),...ids.editor.querySelectorAll(s),ids.workspace,ids.refresh]};
 const ctx={document,fetch,AbortController,URLSearchParams,Intl,crypto:require('node:crypto').webcrypto,setTimeout,clearTimeout,window:{confirm:()=>true},FormData:class {constructor(form){return form.querySelectorAll('input,select').filter(n=>n.name&&!n.disabled).map(n=>[n.name,String(n.value)]);}}};
 vm.createContext(ctx);let source=fs.readFileSync('sales/sales.js','utf8');source=source.replace('refresh(true);\n})();','globalThis.app={state,api,load,reload,refresh,render,card,openEditor,mutate,writable,invalidateAccess};\n})();');vm.runInContext(source,ctx);
 const app=ctx.app;Object.assign(app.state,{workspace:W,workspaces:[{id:W,name:'Workspace',role:'member'}],ready:true,rows:{processes:[{id:P,title:'Custom task',kind:'task'}],stages:[{id:T,process_id:P,title:'Review',position:8},{id:S,process_id:P,title:'Intake',position:2}],tasks:[],dashboard:[{companies:7}]}});
 return {app,ids,fields:()=>Object.fromEntries(ids['editor-fields'].querySelectorAll('input,select').map(n=>[n.name,n]))};
}
const row=()=>({id:ID,title:'Private task',version:4,process_id:P,stage_id:S,status:'done',opportunity_id:null});
const plain=x=>JSON.parse(JSON.stringify(x));
const tick=()=>new Promise(r=>setImmediate(r));
test('task board uses process/stage position, explicit no-process and unknown buckets, not status',()=>{const c=client();c.app.state.rows.tasks=[row(),{...row(),id:'free',title:'Free',process_id:null,stage_id:null},{...row(),id:'unknown',title:'Unknown',process_id:'other'}];c.app.render();const section=c.ids.content.children.find(n=>n.id==='tasks'),board=section.children.find(n=>n.className==='board');assert.deepEqual(board.children.map(n=>n.children[0].textContent),['Custom task / Intake — 1','Custom task / Review — 0','Senza processo — 1','Fase non assegnata / non caricata — 1']);assert.equal(board.children[0].querySelector('article').children[0].textContent,'Private task');});
test('task stage action sends coherent versioned update without inventing status mapping',async()=>{const posts=[];const c=client(async(_,opts)=>{if(opts.body)posts.push(JSON.parse(opts.body));return response();});const card=c.app.card('tasks',row());card.querySelector('select').value=T;await card.querySelectorAll('button').find(n=>n.textContent==='Conferma cambio fase').listeners.click();assert.deepEqual(posts[0].data,{id:ID,version:4,process_id:P,stage_id:T});assert.equal(posts[0].action,'update');assert.doesNotThrow(()=>command(posts[0]));});
test('viewer task phase controls disabled and retained callbacks cannot write',async()=>{let calls=0;const c=client(async()=>{calls++;return response();});c.app.state.workspaces[0].role='viewer';const card=c.app.card('tasks',row());assert.ok(card.querySelector('select').disabled);card.querySelector('select').value=T;await card.querySelectorAll('button')[0].listeners.click();assert.equal(calls,0);});
for(const entity of ['contacts','leads','opportunities','tasks'])test('update editor preserves current and unloaded relations: '+entity,()=>{const c=client();const r={...row(),name:'Contact',company_id:ID,contact_id:T,opportunity_id:S,amount_cents:12345};c.app.openEditor(entity,r);const f=c.fields();if(entity!=='tasks')assert.equal(f.company_id.value,ID);if(['leads','opportunities'].includes(entity))assert.equal(f.contact_id.value,T);if(entity==='opportunities')assert.equal(f.amount_cents.value,12345);if(entity==='tasks')assert.equal(f.opportunity_id.value,S);});
test('update form posts zero/null and original version; task can clear process pair',async()=>{for(const entity of ['opportunities','tasks']){const posts=[];const c=client(async(_,opts)=>{if(opts.body)posts.push(JSON.parse(opts.body));return response(409);});c.app.openEditor(entity,{...row(),amount_cents:42,company_id:ID,contact_id:T,opportunity_id:S});const f=c.fields();if(entity==='opportunities'){f.amount_cents.value='0';f.company_id.value='';f.contact_id.value='';}else{f.opportunity_id.value='';f.process_id.value='';f.process_id.listeners.change();}c.ids['editor-form'].listeners.submit({preventDefault(){},currentTarget:c.ids['editor-form']});await tick();assert.equal(posts[0].data.version,4);if(entity==='opportunities'){assert.equal(posts[0].data.amount_cents,0);assert.equal(posts[0].data.company_id,null);assert.equal(posts[0].data.contact_id,null);}else{assert.equal(posts[0].data.opportunity_id,null);assert.equal(posts[0].data.process_id,null);assert.equal(posts[0].data.stage_id,null);}assert.doesNotThrow(()=>command(posts[0]));}});
for(const status of [401,403])test('mutation '+status+' clears access, private DOM, editor and blocks writes',async()=>{let calls=0;const c=client(async()=>{calls++;return {status,ok:false,json:async()=>{throw Error('non JSON');}};});c.app.render();c.app.openEditor('tasks',row());await c.app.mutate('tasks','update',{id:ID,version:4,title:'X'},'Confirm');assert.equal(c.app.state.ready,false);assert.equal(c.app.state.workspace,null);assert.deepEqual(plain(c.app.state.workspaces),[]);assert.deepEqual(plain(c.app.state.rows),{});assert.equal(c.ids.content.children.length,0);assert.equal(c.ids.editor.open,false);assert.equal(c.ids['editor-fields'].children.length,0);assert.equal(c.ids.workspace.disabled,true);await c.app.mutate('tasks','update',{},'Again');assert.equal(calls,1);await assert.rejects(c.app.api('tasks'),e=>e.status===status);});
test('401 during parallel reload cannot be undone by late data/dashboard responses',async()=>{const pending=[];const c=client(()=>new Promise(resolve=>pending.push(resolve)));const loading=c.app.reload();pending[0](response(401));await tick();for(const resolve of pending.slice(1))resolve(response(200,[{id:ID,title:'Late private',companies:99}]));await loading;assert.equal(c.app.state.ready,false);assert.deepEqual(plain(c.app.state.rows),{});assert.equal(c.ids.content.children.length,0);});
test('late successful mutation after invalidation cannot reload or restore private state',async()=>{let resolve,calls=0;const c=client(()=>{calls++;return new Promise(r=>resolve=r);});const saving=c.app.mutate('tasks','update',{id:ID,version:4,title:'X'},'Confirm');c.app.invalidateAccess();resolve(response());await saving;assert.equal(calls,1);assert.equal(c.app.state.ready,false);assert.equal(c.ids.content.children.length,0);});
for(const kind of ['conflict','timeout'])test(kind+' preserves legitimate data and editor without auth invalidation',async()=>{const c=client(async()=>{if(kind==='timeout')throw Object.assign(Error('timeout'),{name:'AbortError'});return response(409);});c.app.render();c.app.openEditor('tasks',row());await c.app.mutate('tasks','update',{id:ID,version:4,title:'X'},'Confirm');assert.equal(c.app.state.ready,true);assert.equal(c.app.state.workspace,W);assert.ok(c.app.state.rows.dashboard);assert.equal(c.ids.editor.open,true);assert.ok(c.ids['editor-fields'].children.length);await assert.rejects(c.app.api('tasks'),e=>e.status===(kind==='conflict'?409:0));});
test('API task phase update retains ACL and rejects incoherent process/stage',async()=>{assert.throws(()=>command({workspace:W,entity:'tasks',action:'update',data:{id:ID,version:4,stage_id:T}}));let writes=0;const handler=createHandler({getSessionUser:()=>({uid:1}),getStore:()=>({membership:async()=>({role:'viewer'}),command:async()=>{writes++;}})});const res={setHeader(){},status(n){this.code=n;return this;},json(){}};await handler({method:'POST',headers:{'content-type':'application/json','x-radix-sales':'1'},body:{workspace:W,entity:'tasks',action:'update',data:{id:ID,version:4,process_id:P,stage_id:T}}},res);assert.equal(res.code,403);assert.equal(writes,0);});
