/* RADIX PM demo — synthetic data, memory only, no I/O. */
(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory();else root.RadixPM=factory();})(typeof globalThis!=='undefined'?globalThis:this,function(){
'use strict';
const statuses=['Da fare','In corso','In revisione','Completato'];
function seed(){return {projects:[{id:'p1',name:'Doc Capital',note:'Nome del pilota · dati interamente sintetici',subprojects:[{id:'s1',name:'Discovery & governance'},{id:'s2',name:'Workspace operativo'}]}],tasks:[{id:'t1',project:'p1',subproject:'s1',title:'Confermare perimetro del pilota',owner:'Elena Rossi',due:'2026-10-12',status:'Completato',dependencies:[],approvalRequired:true,approved:true,milestone:true,agent:'Nessuno',recurrence:'Nessuna',documents:['Brief pilota — esempio sintetico'],decisions:['Perimetro dimostrativo confermato.'],history:['Baseline demo: approvazione simulata inclusa nei dati sintetici.']},{id:'t2',project:'p1',subproject:'s1',title:'Validare matrice responsabilità',owner:'Marco Bianchi',due:'2026-10-15',status:'In revisione',dependencies:['t1'],approvalRequired:true,approved:false,milestone:false,agent:'Analista governance · assegnato, non live',recurrence:'Settimanale · solo descrizione',documents:['Matrice RACI — esempio sintetico'],decisions:['Approvazione umana richiesta prima della chiusura.'],history:['Baseline demo: bozza predisposta, nessun agente eseguito.']},{id:'t3',project:'p1',subproject:'s2',title:'Preparare workspace documentale',owner:'Sara Conti',due:'2026-10-19',status:'Da fare',dependencies:['t2'],approvalRequired:false,approved:false,milestone:false,agent:'Curatore documenti · assegnato, non live',recurrence:'Nessuna',documents:['Indice documenti — segnaposto'],decisions:[],history:['Baseline demo: attività dipendente dalla matrice responsabilità.']},{id:'t4',project:'p1',subproject:'s2',title:'Revisione finale del pilota',owner:'Elena Rossi',due:'2026-10-22',status:'Da fare',dependencies:['t3'],approvalRequired:true,approved:false,milestone:true,agent:'Revisore qualità · assegnato, non live',recurrence:'Mensile · solo descrizione',documents:[],decisions:['Il passaggio live è fuori ambito.'],history:['Baseline demo: milestone creata.']}],nextId:5};}
function get(state,id){const task=state.tasks.find(t=>t.id===id);if(!task)throw new Error('Attività non trovata.');return task;}
function blockers(state,task){return task.dependencies.filter(id=>get(state,id).status!=='Completato');}
function changeStatus(state,id,status){const task=get(state,id);if(!statuses.includes(status))throw new Error('Stato non valido.');if(status===task.status)return task;if(status!=='Da fare'&&blockers(state,task).length)throw new Error('Completa prima le dipendenze.');if(status==='Completato'&&task.approvalRequired&&!task.approved)throw new Error('Serve una approvazione esplicita prima di completare.');if(task.status==='Completato'&&state.tasks.some(t=>t.dependencies.includes(id)&&t.status!=='Da fare'))throw new Error('Riporta prima a Da fare le attività dipendenti.');task.history.push('Cambio stato simulato: '+task.status+' → '+status+'.');if(task.status==='Completato'){task.approved=false;task.history.push('Riapertura: approvazione precedente revocata.');}task.status=status;return task;}
function approve(state,id,explicit){const task=get(state,id);if(explicit!==true)throw new Error('Conferma esplicitamente l’approvazione.');if(!task.approvalRequired)throw new Error('Questa attività non richiede approvazione.');if(task.status!=='In revisione')throw new Error('Porta prima l’attività In revisione.');if(blockers(state,task).length)throw new Error('Completa prima le dipendenze.');if(task.approved)return task;task.approved=true;task.history.push('Approvazione esplicita simulata dall’utente locale; nessuna identità verificata.');return task;}
function create(state,input){const title=String(input.title||'').trim(),owner=String(input.owner||'').trim(),due=String(input.due||'');if(!title||title.length>120||!owner||owner.length>80)throw new Error('Titolo (max 120) e responsabile (max 80) obbligatori.');if(!/^\d{4}-\d{2}-\d{2}$/.test(due)||!Number.isFinite(Date.parse(due))||new Date(due).toISOString().slice(0,10)!==due)throw new Error('Inserisci una scadenza valida.');const project=state.projects.find(p=>p.id===input.project);if(!project||!project.subprojects.some(s=>s.id===input.subproject))throw new Error('Progetto o sottoprogetto non valido.');const dependencies=[...new Set(input.dependencies||[])];dependencies.forEach(id=>get(state,id));const task={id:'t'+state.nextId++,project:project.id,subproject:input.subproject,title,owner,due,status:'Da fare',dependencies,approvalRequired:input.approvalRequired===true,approved:false,milestone:input.milestone===true,agent:'Nessuno',recurrence:input.recurrence==='Settimanale'?'Settimanale · solo descrizione':'Nessuna',documents:[],decisions:[],history:['Creata localmente nella demo; nessun salvataggio persistente.']};state.tasks.push(task);return task;}
function filter(state,criteria){criteria=criteria||{};const q=String(criteria.query||'').trim().toLocaleLowerCase('it');return state.tasks.filter(t=>(!criteria.status||t.status===criteria.status)&&(!criteria.subproject||t.subproject===criteria.subproject)&&(!criteria.owner||t.owner===criteria.owner)&&(!criteria.milestone||t.milestone)&&(!q||(t.title+' '+t.owner+' '+t.id).toLocaleLowerCase('it').includes(q)));}
return {seed,statuses,blockers,changeStatus,approve,create,filter};
});
